Update build.yml

diff --git a/.github/workflows/build.yml b/.github/workflows/build.yml
--- a/.github/workflows/build.yml
+++ b/.github/workflows/build.yml
@@ -154,9 +154,9 @@ jobs:
           echo "Sending message: $MESSAGE"
 
           curl -s -X POST "https://api.telegram.org/bot${{ secrets.TG_TOKEN }}/sendMessage" \
-            -d "chat_id=717601421" \
-            -d "text=${MESSAGE}" \
-            -d "disable_web_page_preview=true" \
-            -d "parse_mode=HTML" || echo "Telegram notification failed"
+            -d chat_id=717601421 \
+            --data-urlencode text="${MESSAGE}" \
+            -d disable_web_page_preview=true \
+            -d parse_mode=HTML || echo "Telegram notification failed"
 
           echo "Notification sent!"
